apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray
spec:
  selector:
    matchLabels:
      app: v2ray
  replicas: 1
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      containers:
        - name: v2ray
          image: oceancn/v2ray-openshift
          imagePullPolicy: Always      
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 900m
              memory: 512Mi
          ports:
            - containerPort: 8080               
